kiwiproject/dropwizard-service-utilities

- pom.xml
- src/main/java/org/kiwiproject/dropwizard/util/startup/SystemExecutioner.java
> Add SystemExecutioner

- src/main/java/org/kiwiproject/dropwizard/util/server/DropwizardConnectors.java
- src/test/java/org/kiwiproject/dropwizard/util/server/DropwizardConnectorsTest.java
> Add DropwizardConnectors

- src/main/java/org/kiwiproject/dropwizard/util/startup/AllowablePortRange.java
- src/main/java/org/kiwiproject/dropwizard/util/startup/PortRangeInfo.java
- src/test/java/org/kiwiproject/dropwizard/util/startup/AllowablePortRangeTest.java
- src/test/java/org/kiwiproject/dropwizard/util/startup/PortRangeInfoTest.java
> Add port range info

- pom.xml
- src/main/java/org/kiwiproject/dropwizard/util/exception/NoAvailablePortException.java
- src/main/java/org/kiwiproject/dropwizard/util/server/DropwizardConnectors.java
- src/main/java/org/kiwiproject/dropwizard/util/startup/PortAssigner.java
- src/test/java/org/kiwiproject/dropwizard/util/server/DropwizardConnectorsTest.java
- src/test/java/org/kiwiproject/dropwizard/util/startup/PortAssignerTest.java
> Add PortAssigner

- pom.xml
- src/main/java/org/kiwiproject/dropwizard/util/startup/StartupLockInfo.java
- src/main/java/org/kiwiproject/dropwizard/util/startup/StartupLocker.java
- src/main/java/org/kiwiproject/dropwizard/util/startup/SystemExecutioner.java
- src/main/java/org/kiwiproject/dropwizard/util/startup/listener/StartupJettyLifeCycleListener.java
- src/main/java/org/kiwiproject/dropwizard/util/startup/listener/StartupWithLockJettyLifeCycleListener.java
- src/test/java/org/kiwiproject/dropwizard/util/startup/StartupLockInfoTest.java
- src/test/java/org/kiwiproject/dropwizard/util/startup/StartupLockerTest.java
- src/test/java/org/kiwiproject/dropwizard/util/startup/listener/StartupJettyLifeCycleListenerTest.java
- src/test/java/org/kiwiproject/dropwizard/util/startup/listener/StartupWithLockJettyLifeCycleListenerTest.java
Add the following listeners as well:
* StartupJettyLifeCycleListener
* StartupWithLockJettyLifeCycleListener
Bump kiwi-parent, kiwi, kiwi-test
Add dropwizard-curator
Closes #5
> Add StartupLocker

- pom.xml
- src/main/java/org/kiwiproject/dropwizard/util/lifecycle/ConnectorLoggingServerLifecycleListener.java
- src/main/java/org/kiwiproject/dropwizard/util/lifecycle/ProcessIdLoggingServerLifecycleListener.java
- src/main/java/org/kiwiproject/dropwizard/util/lifecycle/ServerStatusServerLifecycleListener.java
- src/main/java/org/kiwiproject/dropwizard/util/lifecycle/StandardLifecycles.java
- src/test/java/org/kiwiproject/dropwizard/util/lifecycle/ConnectorLoggingServerLifecycleListenerTest.java
- src/test/java/org/kiwiproject/dropwizard/util/lifecycle/ProcessIdLoggingServerLifecycleListenerTest.java
- src/test/java/org/kiwiproject/dropwizard/util/lifecycle/ServerStatusServerLifecycleListenerTest.java
- src/test/java/org/kiwiproject/dropwizard/util/lifecycle/StandardLifecyclesTest.java
> Add StandardLifecycles utility

- src/main/java/org/kiwiproject/dropwizard/util/environment/StandardEnvironmentConfigurations.java
- src/test/java/org/kiwiproject/dropwizard/util/environment/StandardEnvironmentConfigurationsTest.java
> Add StandardEnvironmentConfigurations

- src/main/java/org/kiwiproject/dropwizard/util/metrics/ServerLoadFetcher.java
- src/main/java/org/kiwiproject/dropwizard/util/metrics/ServerLoadGauge.java
- src/main/java/org/kiwiproject/dropwizard/util/task/ServerLoadTask.java
- src/test/java/org/kiwiproject/dropwizard/util/metrics/ServerLoadFetcherTest.java
- src/test/java/org/kiwiproject/dropwizard/util/metrics/ServerLoadGaugeTest.java
- src/test/java/org/kiwiproject/dropwizard/util/task/ServerLoadTaskTest.java
This includes:
* fetcher to call out to uptime
* gauge to track load averages in metrics
* server task to expose an endpoint to retrieve current average
Closes #20
> Add server load utilities

- pom.xml
- src/main/java/org/kiwiproject/dropwizard/util/config/KeystoreConfig.java
- src/main/java/org/kiwiproject/dropwizard/util/health/keystore/BasicCertInfo.java
- src/main/java/org/kiwiproject/dropwizard/util/health/keystore/CertStatus.java
- src/main/java/org/kiwiproject/dropwizard/util/health/keystore/ExpiringKeystoreHealthCheck.java
- src/main/java/org/kiwiproject/dropwizard/util/health/keystore/KeystoreHealthResults.java
- src/test/java/org/kiwiproject/dropwizard/util/health/keystore/CertStatusTest.java
- src/test/java/org/kiwiproject/dropwizard/util/health/keystore/ExpiringKeystoreHealthCheckTest.java
- src/test/java/org/kiwiproject/dropwizard/util/health/keystore/KeystoreHealthResultsTest.java
> Add ExpiringKeystoreHealthCheck and supporting classes

- src/main/java/org/kiwiproject/dropwizard/util/metrics/ServerLoadFetcher.java
> Update input stream reader to use KiwiIO

- src/main/java/org/kiwiproject/dropwizard/util/health/HttpConnectionsHealthCheck.java
- src/test/java/org/kiwiproject/dropwizard/util/health/HttpConnectionsHealthCheckTest.java
> Add HttpConnectionsHealthCheck

- src/main/java/org/kiwiproject/dropwizard/util/resource/ConfigResource.java
- src/test/java/org/kiwiproject/dropwizard/util/resource/ConfigResourceTest.java
> Add ConfigResource

- src/main/java/org/kiwiproject/dropwizard/util/config/JacksonConfig.java
- src/main/java/org/kiwiproject/dropwizard/util/health/UnknownPropertiesHealthCheck.java
- src/main/java/org/kiwiproject/dropwizard/util/jackson/StandardJacksonConfigurations.java
- src/test/java/org/kiwiproject/dropwizard/util/health/UnknownPropertiesHealthCheckTest.java
- src/test/java/org/kiwiproject/dropwizard/util/jackson/StandardJacksonConfigurationsTest.java
> Add StandardJacksonConfigurations and UnknownPropertiesHealthCheck

- src/main/java/org/kiwiproject/dropwizard/util/exception/EarlyEofExceptionMapper.java
- src/main/java/org/kiwiproject/dropwizard/util/exception/EmptyOptionalExceptionMapper.java
- src/main/java/org/kiwiproject/dropwizard/util/exception/JerseyViolationExceptionMapper.java
- src/main/java/org/kiwiproject/dropwizard/util/exception/JsonProcessingExceptionMapper.java
- src/main/java/org/kiwiproject/dropwizard/util/exception/LoggingExceptionMapper.java
- src/main/java/org/kiwiproject/dropwizard/util/exception/StandardExceptionMappers.java
- src/test/java/org/kiwiproject/dropwizard/util/exception/EarlyEofExceptionMapperTest.java
- src/test/java/org/kiwiproject/dropwizard/util/exception/EmptyOptionalExceptionMapperTest.java
- src/test/java/org/kiwiproject/dropwizard/util/exception/ErrorMessageAssertion.java
- src/test/java/org/kiwiproject/dropwizard/util/exception/ErrorMessageAssertions.java
- src/test/java/org/kiwiproject/dropwizard/util/exception/JerseyViolationExceptionMapperTest.java
- src/test/java/org/kiwiproject/dropwizard/util/exception/JsonProcessingExceptionMapperTest.java
- src/test/java/org/kiwiproject/dropwizard/util/exception/LoggingExceptionMapperTest.java
- src/test/java/org/kiwiproject/dropwizard/util/exception/StandardExceptionMappersTest.java
> Add StandardExceptionMappers and all the overridden mappers

- src/main/java/org/kiwiproject/dropwizard/util/health/ProcessGrepHealthCheck.java
- src/test/java/org/kiwiproject/dropwizard/util/health/ProcessGrepHealthCheckTest.java
> Add ProcessGrepHealthCheck

- src/main/java/org/kiwiproject/dropwizard/util/health/ProcessKillHealthCheck.java
- src/test/java/org/kiwiproject/dropwizard/util/health/ProcessKillHealthCheckTest.java
> Add ProcessKillHealthCheck

- src/main/java/org/kiwiproject/dropwizard/util/health/ProcessLaunchHealthCheck.java
- src/test/java/org/kiwiproject/dropwizard/util/health/ProcessLaunchHealthCheckTest.java
> Add ProcessLaunchHealthCheck

- src/main/java/org/kiwiproject/dropwizard/util/health/MongoHealthCheck.java
- src/test/java/org/kiwiproject/dropwizard/util/health/MongoHealthCheckTest.java
> Add MongoHealthCheck

- src/main/java/org/kiwiproject/dropwizard/util/health/ServerErrorHealthCheck.java
- src/test/java/org/kiwiproject/dropwizard/util/health/ServerErrorHealthCheckTest.java
> Add ServerErrorHealthCheck

- pom.xml
- src/main/java/org/kiwiproject/dropwizard/util/health/ServicePingHealthCheck.java
- src/test/java/org/kiwiproject/dropwizard/util/health/ServicePingHealthCheckTest.java
> Add ServicePingHealthCheck

- src/main/java/org/kiwiproject/dropwizard/util/config/JobSchedule.java
- src/main/java/org/kiwiproject/dropwizard/util/job/JobErrorHandler.java
- src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJob.java
- src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobTest.java
> Add MonitoredJob and JobSchedule

- src/main/java/org/kiwiproject/dropwizard/util/health/MonitoredJobHealthCheck.java
- src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJob.java
- src/test/java/org/kiwiproject/dropwizard/util/health/MonitoredJobHealthCheckTest.java
Updated Getters on MonitoredJob
Closes #47
> Add MonitoredJobHealthCheck

- src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJobs.java
- src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobsTest.java
> Add MonitoredJobs utility

- pom.xml
- src/main/java/org/kiwiproject/dropwizard/util/server/DropwizardConnectors.java
- src/test/java/org/kiwiproject/dropwizard/util/server/DropwizardConnectorsTest.java
> Replace ConnectorType#fromClass with #forHttpConnectorFactory

- src/main/java/org/kiwiproject/dropwizard/util/jackson/StandardJacksonConfigurations.java
* Add additional explanation to registerAllStandardJacksonConfigurations
documentation in StandardJacksonConfigurations
* IntelliJ also decided to reformat some of the Javadocs, etc. when I
reformatted the class
> Enhance StandardJacksonConfigurations javadocs

- pom.xml
* Bump service-discovery-client from 0.10.0 to 0.11.0
* Bump registry-aware-jersey-client from 0.8.0 to 0.9.0
Closes #82 
Closes #83
> Bump various kiwiproject versions

- src/main/java/org/kiwiproject/dropwizard/util/config/JobSchedule.java
- src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJob.java
- src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJobs.java
- src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobTest.java
- src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobsTest.java
* Add `@With` to errorHandler and timeout on MonitoredJob
* Add `registerJob` method that takes a pre-built MonitoredJob on MonitoredJobs
Closes #85
> Enhance MonitoredJob and MonitoredJobs

- src/main/java/org/kiwiproject/dropwizard/util/health/HttpConnectionsHealthCheck.java
- src/main/java/org/kiwiproject/dropwizard/util/health/MongoHealthCheck.java
- src/main/java/org/kiwiproject/dropwizard/util/health/ProcessGrepHealthCheck.java
- src/main/java/org/kiwiproject/dropwizard/util/health/ProcessKillHealthCheck.java
- src/main/java/org/kiwiproject/dropwizard/util/health/ProcessLaunchHealthCheck.java
- src/main/java/org/kiwiproject/dropwizard/util/health/ServerErrorHealthCheck.java
- src/main/java/org/kiwiproject/dropwizard/util/health/ServicePingHealthCheck.java
- src/main/java/org/kiwiproject/dropwizard/util/health/UnknownPropertiesHealthCheck.java
> Add DEFAULT_NAME constant to health checks

- pom.xml
* Bump service-discovery-client from 0.11.0 to 0.12.0
* Bump registry-aware-jersey-client from 0.9.0 to 0.10.0
* Bump junit-pioneer from 1.1.0 to 1.2.0
> Bump several dependencies

- src/main/java/org/kiwiproject/dropwizard/util/lifecycle/ConnectorLoggingServerLifecycleListener.java
- src/main/java/org/kiwiproject/dropwizard/util/server/DropwizardConnectors.java
* Replace lambda with instanceof with method reference in
ConnectorLoggingServerLifecycleListener and DropwizardConnectors
(Sonar rule java:S1612)
> Sonar cleanup

- src/test/java/org/kiwiproject/dropwizard/util/health/keystore/ExpiringKeystoreHealthCheckTest.java
* Change ExpiringKeystoreHealthCheckTest so that it waits up to five
seconds when creating a new keystore
* Log an INFO message if process exits within 5 seconds, otherwise WARN
* Update debug logging statements to clarify what is stdout and stderr
of the keytool processes
* Remove redundant "throws Exception" from tests
Background for this update:
While investigating the failing tests in #104 I temporarily changed the
test code to copy each keystore for each test from the temp directory to
a permanent location for examination. But immediately after the
waitForExit call in createTemporaryKeystore, the Files#copy call was
failing b/c with a FileNotFoundException! So, I logged the exit code and
found that it was an empty Optional, which is what waitForExit returns
if the timeout occurs …
> Wait up to 5 seconds for keytool exit in ExpiringKeystoreHealthCheckTest

- src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJob.java
- src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJobs.java
- src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobTest.java
* Change from Function<MonitoredJob, Boolean> to Predicate<MonitoredJob>
in MonitoredJob and MonitoredJobs
* Added a bunch of javadocs etc.
* Was able to remove the null-case test in MonitoredJobTest since the
Predicate returns boolean (whereas the Function returned Boolean
which annoyingly could be null)
Closes #110
> Change MonitoredJob decision function from Function to Predicate

- src/test/java/org/kiwiproject/dropwizard/util/health/keystore/ExpiringKeystoreHealthCheckTest.java
> Fix daylight savings issue in ExpiringKeystoreHealthCheckTest

- .github/workflows/build.yml
- pom.xml
* Bump zookeeper to 3.7.0
* Bump curator to 5.1.0
Closes #145
> Support Java 16

- pom.xml
See https://github.com/kiwiproject/dropwizard-mongo-migrations/issues/13
> Bump spring version from 5.3.9 to 5.3.13

- src/test/java/org/kiwiproject/dropwizard/util/jackson/StandardJacksonConfigurationsTest.java
> Add timestamp serialization test in StandardJacksonConfigurationsTest

- src/main/java/org/kiwiproject/dropwizard/util/jackson/StandardJacksonConfigurations.java
- src/test/java/org/kiwiproject/dropwizard/util/jackson/StandardJacksonConfigurationsTest.java
* Add new tests of JAXBElement serialization of both nil and non-nil
values
* Improve javadoc of StandardJacksonConfigurations
Closes #217
Closes #284
> Add tests of JAXBElement serialization and improve javadoc

- src/main/java/org/kiwiproject/dropwizard/util/resource/ConfigResource.java
- src/test/java/org/kiwiproject/dropwizard/util/resource/ConfigResourceTest.java
> Disable FAIL_ON_EMPTY_BEANS serialization feature in ConfigResource

- src/main/java/org/kiwiproject/dropwizard/util/startup/AllowablePortRange.java
> Add toString to AllowablePortRange

- src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJob.java
- src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobTest.java
* Enhance messages logged by handleExceptionSafely to include the exception type, and if present, the root cause. Also mention that the stack trace logged by CatchingRunnable will be ABOVE this log message.
* Add 'tests' which exercise the two causes - an Exception with a separate root cause, and one without one, i.e. such that the root cause is itself.
* Change soft assertions to use assertAll from Jupiter
Closes #391
> Enhance exception logging in MonitoredJob#handleExceptionSafely

- src/main/java/org/kiwiproject/dropwizard/util/health/MonitoredJobHealthCheck.java
- src/test/java/org/kiwiproject/dropwizard/util/health/MonitoredJobHealthCheckTest.java
> Include the last exception in details of MonitoredJobHealthCheck

- src/main/java/org/kiwiproject/dropwizard/util/startup/SystemExecutioner.java
- src/test/java/org/kiwiproject/dropwizard/util/startup/SystemExecutionerTest.java
> Change SystemExecutioner constructor to validate ExecutionStrategy is not null

- src/main/java/org/kiwiproject/dropwizard/util/startup/PortAssigner.java
> Explain restriction on ServerFactory in PortAssigner javadoc

- src/main/java/org/kiwiproject/dropwizard/util/health/ServicePingHealthCheck.java
- src/test/java/org/kiwiproject/dropwizard/util/health/ServicePingHealthCheckTest.java
* Extract method: makeGetRequest
* Add test that creates a health check and overrides makeGetRequest to simulate an exception
> Improve ServicePingHealthCheckTest

- src/main/java/org/kiwiproject/dropwizard/util/bundle/DynamicPortsBundle.java
- src/main/java/org/kiwiproject/dropwizard/util/bundle/DynamicPortsConfiguration.java
- src/main/java/org/kiwiproject/dropwizard/util/bundle/DynamicPortsConfigured.java
- src/main/java/org/kiwiproject/dropwizard/util/bundle/PortAssigners.java
- src/test/java/org/kiwiproject/dropwizard/util/bundle/CountingLocalPortChecker.java
- src/test/java/org/kiwiproject/dropwizard/util/bundle/DynamicPortsBundleForStaticPortsTest.java
- src/test/java/org/kiwiproject/dropwizard/util/bundle/DynamicPortsBundleTest.java
- src/test/java/org/kiwiproject/dropwizard/util/bundle/DynamicPortsConfigurationTest.java
- src/test/java/org/kiwiproject/dropwizard/util/bundle/MyDynamicPortsApp.java
- src/test/java/org/kiwiproject/dropwizard/util/bundle/MyDynamicPortsConfig.java
- src/test/java/org/kiwiproject/dropwizard/util/bundle/PortAssignersTest.java
- src/test/resources/DynamicPortsConfigurationTest/dynamic-ports-config-all-values-dynamic.yml
- src/test/resources/DynamicPortsConfigurationTest/dynamic-ports-config-all-values-not-dynamic.yml
- src/test/resources/DynamicPortsConfigurationTest/dynamic-ports-config-only-tls.yml
* Add DynamicPortsConfiguration, which contains dynamic port configuration
* AddDynamicPortsConfigured interface, which defines how the bundle gets the configuration
* Add DynamicPortsBundle which assigns random ports
* Add package-private utility class PortAssigners
Closes https://github.com/kiwiproject/dropwizard-service-utilities/issues/458
> Add dynamic ports bundle

- src/main/java/org/kiwiproject/dropwizard/util/bundle/StartupLockBundle.java
This fixes a javadoc error which prevented a release to Maven Central
> Fix Javadoc in StartupLockBundle

- src/main/java/org/kiwiproject/dropwizard/util/exception/JsonExceptionMappers.java
- src/main/java/org/kiwiproject/dropwizard/util/exception/JsonProcessingExceptionMapper.java
- src/main/java/org/kiwiproject/dropwizard/util/exception/RuntimeJsonExceptionMapper.java
- src/test/java/org/kiwiproject/dropwizard/util/exception/JsonProcessingExceptionMapperTest.java
- src/test/java/org/kiwiproject/dropwizard/util/exception/RuntimeJsonExceptionMapperTest.java
* Add RuntimeJsonExceptionMapper
* Extract duplicate code to package-private JsonExceptionMapper
* Add response assertions to JsonProcessingExceptionMapperTest 
Closes #478
> Add ExceptionMapper for RuntimeJsonException

- src/main/java/org/kiwiproject/dropwizard/util/exception/StandardExceptionMappers.java
- src/test/java/org/kiwiproject/dropwizard/util/exception/StandardExceptionMappersTest.java
> Register RuntimeJsonExceptionMapper in StandardExceptionMappers

- src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobsTest.java
* Remove unnecessary parentheses around lambda parameter
* Don't hide a field
> Sonar cleanup: MonitoredJobsTest

- pom.xml
- src/main/java/org/kiwiproject/dropwizard/util/health/CachingHealthCheck.java
- src/main/java/org/kiwiproject/dropwizard/util/health/UrlHealthCheck.java
- src/test/java/org/kiwiproject/dropwizard/util/health/CachingHealthCheckTest.java
- src/test/java/org/kiwiproject/dropwizard/util/health/UrlHealthCheckTest.java
- src/test/java/org/kiwiproject/dropwizard/util/okhttp3/mockwebserver/RecordedRequests.java
* Add health check to check a URL
* Add a caching health check
Closes #491
Closes #492
> Add new health checks

- src/main/java/org/kiwiproject/dropwizard/util/health/CachingHealthCheck.java
- src/test/java/org/kiwiproject/dropwizard/util/exception/StandardExceptionMappersTest.java
* Remove redundant throws clause from CachingHealthCheck#check
* Suppress unused method warning in StandardExceptionMappersTest
Closes #549
Closes #550
> Code cleanup

- src/main/java/org/kiwiproject/dropwizard/util/startup/IncrementingFreePortFinder.java
- src/test/java/org/kiwiproject/dropwizard/util/startup/IncrementingFreePortFinderTest.java
> Fix of-by-one error in IncrementingPortFinder

- src/main/java/org/kiwiproject/dropwizard/util/health/MonitoredJobHealthCheck.java
- src/test/java/org/kiwiproject/dropwizard/util/health/MonitoredJobHealthCheckTest.java
> Report human-readable durations in MonitoredJobHealthCheck error messages

- pom.xml
> Remove the explicit okhttp version (inherits from BOM now)
