pom.xml
src/main/java/org/kiwiproject/dropwizard/util/health/ServerErrorHealthCheck.java
src/test/java/org/kiwiproject/dropwizard/util/health/ServerErrorHealthCheckTest.java

* Update ServerErrorHealthCheck to show only one decimal place in the
approximateCount result detail
* Add JUnit Pioneer 1.1.0 with exclusions since they are only on
Jupiter 5.5.2 instead of 5.7.0
* Change ServerErrorHealthCheckTest to use Pioneer's @DoubleRangeSource
* Move kiwi-test dependency to its correct order below the "j" deps
Closes #54
Closes #57

Add JUnit Pioneer; reduce digits shown in approximateCount detail

---

pom.xml

For whatever reason, junit 3.8 is brought in transitively jline which is
brought in from ZooKeeper.

Fix Maven convergence error with junit

---

src/test/java/org/kiwiproject/dropwizard/util/jackson/StandardJacksonConfigurationsTest.java

* Add assertion in StandardJacksonConfigurationsTest to ensure the
ObjectMapper returned by registerAllStandardJacksonConfigurations

Ensure registerAllStandardJacksonConfigurations returns correct mapper

---

src/main/java/org/kiwiproject/dropwizard/util/startup/listener/StartupJettyLifeCycleListener.java
src/main/java/org/kiwiproject/dropwizard/util/startup/listener/StartupWithLockJettyLifeCycleListener.java

* Log the Throwable cause in lifeCycleFailure in both
StartupJettyLifeCycleListener and StartupWithLockJettyLifeCycleListener
* Reformat some lengthy lines in StartupWithLockJettyLifeCycleListener
Closes #70

Log the Throwable provided by Jetty on lifecycle failure

---

src/main/java/org/kiwiproject/dropwizard/util/admin/AdminConfigurator.java
src/main/java/org/kiwiproject/dropwizard/util/resource/ConfigResource.java
src/test/java/org/kiwiproject/dropwizard/util/resource/ConfigResourceTest.java

There is not a need for ConfigResource to be generic since all configurations
will extend Dropwizard's Configuration class
Closes #71

Fix warning when creating ConfigResource

---

pom.xml

* Bump dropwizard-curator from 0.14.0 to 0.15.0
* Bump service-discovery-client from 0.9.0 to 0.10.0
* Bump registry-aware-jersey-client from 0.7.0 to 0.8.0
* Add mongo provided dependency for MongoHealthCheck

Bump various kiwiproject versions

---

pom.xml
src/main/java/org/kiwiproject/dropwizard/util/exception/LoggingExceptionMapper.java
src/test/java/org/kiwiproject/dropwizard/util/exception/LoggingExceptionMapperTest.java

* Handle Hibernate OptimisticEntityLockException and
ConstraintViolationException classes
* Refactor internal logic to use a map from class name to a category
which is then used to select the appropriate response status code.
The only annoying thing is that we don't yet have Java's new
exhaustive compiler check on the switch, so the default arm cannot
be covered with tests.
* Refactor LoggingExceptionMapperTest to use the actual Spring and
Hibernate classes, which allowed us to change the
dataAccessExceptionResponse method to be private
* Add the Spring and Hibernate dependencies with test scope
Closes #48

Handle select Hibernate data exception classes in LoggingExceptionMapper

---

pom.xml
src/main/java/org/kiwiproject/dropwizard/util/startup/ExecutionStrategies.java
src/main/java/org/kiwiproject/dropwizard/util/startup/ExecutionStrategy.java
src/main/java/org/kiwiproject/dropwizard/util/startup/SystemExecutioner.java
src/test/java/org/kiwiproject/dropwizard/util/startup/ExecutionStrategiesTest.java
src/test/java/org/kiwiproject/dropwizard/util/startup/SystemExecutionerTest.java

* Introduce ExecutionStrategy interface as a pluggable strategy for
terminating the JVM (or not terminating in tests, etc.)
* ExecutionStrategies is a factory class that provides several
strategies: a no-op strategy, an exit "flagging" strategy, and a
System.exit strategy.
* SystemExecutioner remains backward-compatible since the no-args
constructor uses the System.exit strategy but provides a way
to construct an instance with some other ExecutionStrategy. This will
mainly be useful in testing situations.
* Note also that even though Jacoco will say the exit() method of
SystemExitExecutionStrategy is not covered by tests, it actually *is*
covered because ExecutionStrategiesTest actually launches a separate
JVM and verifies that it was exited.

Introduce ExecutionStrategy as pluggable strategy to SystemExecutioner

---

src/main/java/org/kiwiproject/dropwizard/util/job/JobErrorHandlers.java
src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJob.java
src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJobs.java
src/test/java/org/kiwiproject/dropwizard/util/job/JobErrorHandlersTest.java
src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobTest.java
src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobsTest.java

* Remove the withErrorHandler and withTimeout methods from
MonitoredJob which did not actually set the error handler or timeout
since they always created a new instance
* Create a custom builder in MonitoredJobs. We cannot use Lombok for
various reasons, mainly that we want to create an instance of
MonitoredJob not MonitoredJobs, and we want the terminal operation to
be named registerJob() instead of build().
* Add JobErrorHandlers as a static factory for several simple
JobErrorHandler implementations
Closes #100
Closes #106

Rework MonitoredJobs to fix bug when setting error handler or timeout

---

src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJobs.java
src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobsTest.java

This method does NOT accept a ScheduledExecutorService and instead
creates one internally.
Other misc:
* Add some more javadocs
* Rename buildScheduledExecutor to newScheduledExecutor and move it
to the bottom, since the last method in this class uses it
Closes #108

Add registerJob factory method that accepts MonitoredJob and JobSchedule

---

src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJobs.java
src/main/java/org/kiwiproject/dropwizard/util/lifecycle/StandardLifecycles.java
src/test/java/org/kiwiproject/dropwizard/util/concurrent/TestExecutors.java
src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobsTest.java
src/test/java/org/kiwiproject/dropwizard/util/lifecycle/StandardLifecyclesTest.java

* Move newScheduledExecutor from MonitoredJobs to StandardLifecycles
* Update the javadocs in StandardLifecycles since it is no longer just
about setting up lifecycle listeners
* Since MonitoredJobsTest and StandardLifecyclesTest had the same code
to shut down the ScheduledExecutorService, moved that code into a
new shared test utility, TestExecutors, which ensures the executor
is gracefully shut down once the test is finished with it
Closes #109

Make newScheduledExecutor public and move to StandardLifecycles

---

src/main/java/org/kiwiproject/dropwizard/util/metrics/ServerLoadFetcher.java

* Add catch block for InterruptedException in ServerLoadFetcher and
reset the interrupt status, per Sonar rule java:S2142
* I did not add a test for this b/c that would involve the code under
test actually setting the interrupt status of the current Thread,
which I don't think is a good idea (need to investigate whether this
can be done safely in tests...)

Handle InterruptedException in ServerLoadFetcher

---

pom.xml
src/main/java/org/kiwiproject/dropwizard/util/job/JobErrorHandler.java
src/main/java/org/kiwiproject/dropwizard/util/job/JobErrorHandlers.java
src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJob.java
src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobTest.java

* Update Throwable to Exception in MonitoredJob due to breaking changes
in kiwi 0.21.0 which changed CatchingRunnable to only handle Exception
and not Throwable
* Change JobErrorHandler and JobErrorHandlers to only handle Exception
for the same reason kiwi changed CatchingRunnable; Throwable should
not be caught by application code, since it could also catch Error
subclasses such as OutOfMemoryError, etc.
Dependency updates:
* Bump dropwizard-curator from 0.17.0 to 0.18.0
* Bump service-discovery-client from 0.14.0 to 0.15.0
* Bump registry-aware-jersey-client from 0.12.0 to 0.13.0
Closes #115
Closes #123
Closes #124
Closes #125

Update dependencies; updates for breaking kiwi 0.21.0 changes

---

pom.xml

* Remove junit-pioneer dependency since kiwi-parent 0.10.0 includes it
Closes #117

Remove junit-pioneer dependency since it is now redundant

---

src/main/java/org/kiwiproject/dropwizard/util/startup/AllowablePortRange.java

* Make the fields in AllowablePortRange final, but leaving them as
package-private for the moment; they are accessed by PortAssigner
which is in the same package, so I don't have too much heartburn
over this.

Make fields final in AllowablePortRange

---

pom.xml

* Bump dropwizard-curator from 1.0.0 to 1.1.0
* Bump registry-aware-jersey-client from 1.0.0 to 1.1.0
* Remove (now unnecessary) kiwi-test exclusion from dropwizard-curator

Bump dropwizard-curator and registry-aware-jersey-client versions

---

src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJobs.java
src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobsTest.java

This avoids problems if callers want to schedule more granular than one
second. For example, with initial delay of 100 milliseconds and interval
delay of 200 milliseconds, converting to seconds results in both values
being zero in the original code. By converting the delays to nanoseconds
instead, we ensure this problem won't happen.
Fixes #173

Change MonitoredJobs to convert delays to nanoseconds when scheduling

---

src/test/java/org/kiwiproject/dropwizard/util/startup/SystemExecutionerTest.java

* Change shouldExitBeforeGivenWaitTime_WhenWaitingThreadInterrupted to
use isGreaterThanOrEqualTo instead of isGreaterThan
* Add an INFO level log just to see what the nanos and conversion to
milliseconds were during a test run
Closes #183

Change timing assertion in SystemExecutionerTest

---

src/main/java/org/kiwiproject/dropwizard/util/health/MongoHealthCheck.java
src/main/java/org/kiwiproject/dropwizard/util/health/MonitoredJobHealthCheck.java
src/main/java/org/kiwiproject/dropwizard/util/health/ServerErrorHealthCheck.java
src/main/java/org/kiwiproject/dropwizard/util/health/ServicePingHealthCheck.java
src/main/java/org/kiwiproject/dropwizard/util/health/UnknownPropertiesHealthCheck.java
src/test/java/org/kiwiproject/dropwizard/util/health/HttpConnectionsHealthCheckTest.java
src/test/java/org/kiwiproject/dropwizard/util/health/keystore/KeystoreHealthResultsTest.java

* Remove redundant 'throws' clause from health checks
* Rename local var in KeystoreHealthResultsTest that was supposed to
end with a number one
* Remove redundant casts in HttpConnectionsHealthCheckTest

Miscellaneous code cleanup

---

src/main/java/org/kiwiproject/dropwizard/util/startup/listener/StartupJettyLifeCycleListener.java
src/main/java/org/kiwiproject/dropwizard/util/startup/listener/StartupWithLockJettyLifeCycleListener.java

* Replace deprecated AbstractLifeCycle.AbstractLifeCycleListener usages
by implementing LifeCycle.Listener directly (it now has default
methods so there's no need for the abstract class anymore)
Closes #221

Replace deprecated AbstractLifeCycleListener with LifeCycle.Listener

---

pom.xml
src/main/java/org/kiwiproject/dropwizard/util/health/MongoHealthCheck.java
src/test/java/org/kiwiproject/dropwizard/util/health/MongoHealthCheckTest.java
src/test/resources/logback.xml

This is a breaking API change, since the DB class no longer exists
in the Mongo 4.x driver. It was  replaced by MongoDatabase. Thus,
the constructor had to change. The MongoDatabase also does not
contain as much information, e.g. you cannot obtain the host and port
information as you could with DB, which provided a getMongo() method
from which you could obtain a ServerAddress in order to find the host
and port. We decided that information does not add enough value to
require callers to include a host and port, though we could re-evauate
that decision later.
This commit, therefore, changes MongoHealthCheck to work with the
4.x driver. The health check has been using the "dbStats" command which
"returns storage statistics for a given database". The problem with this
is that, from the docs, …

Change MongoHealthCheck to work with 4.x driver

---

src/main/java/org/kiwiproject/dropwizard/util/lifecycle/ProcessIdLoggingServerLifecycleListener.java
src/main/java/org/kiwiproject/dropwizard/util/lifecycle/StandardLifecycles.java
src/test/java/org/kiwiproject/dropwizard/util/lifecycle/ProcessIdLoggingServerLifecycleListenerTest.java
src/test/java/org/kiwiproject/dropwizard/util/lifecycle/StandardLifecyclesTest.java

* Overload addProcessIdLoggingLifecycleListener in StandardLifecycles to
accept a long as well as an OptionalLong, in addition to the existing
Long, for the process ID
* Add constructor in ProcessIdLoggingServerLifecycleListener that
accepts long
Closes #247
Closes #248

StandardLifecycles improvements

---

src/main/java/org/kiwiproject/dropwizard/util/health/keystore/KeystoreHealthResults.java
src/main/java/org/kiwiproject/dropwizard/util/resource/ConfigResource.java
src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobsTest.java

* Remove Slf4j annotations from ConfigResource and MonitoredJobsTest
since neither actually uses the Logger that it provides
* Remove the unused ZoneId static final field from KeystoreHealthResults

Removed unused code

---

src/main/java/org/kiwiproject/dropwizard/util/metrics/ServerLoadFetcher.java
src/test/java/org/kiwiproject/dropwizard/util/metrics/ServerLoadFetcherTest.java

* Fix issue java:S6397 (Character classes in regular expressions should
not contain only one character) in the ServerLoadFetcher load average
Pattern
* Make ServerLoadFetcher#LOAD_AVERAGE_PATTERN case-insensitive
* Update the javadocs on ServerLoadFetcher#get for the return value
and add an implementation note about the match being case-insensitive
* Refactor ServerLoadFetcherTest in the nested class format with
"should" semantics for test names
* Remove character classes around commas in ServerLoadFetcherTest in the
test using an actual OS process
* Change test ServerLoadFetcherTest to be a parameterized test to verify
both Linux and macOS formats, as well as case-insensitive behavior

Sonar: fix regular expression in ServerLoadFetcher

---

src/test/java/org/kiwiproject/dropwizard/util/config/JacksonConfigTest.java

Yes, this is simple, but it verifies what we expect the default values
to be when using the no-args constructor and the builder.

Add JacksonConfigTest

---

src/main/java/org/kiwiproject/dropwizard/util/jackson/StandardJacksonConfigurations.java

Since the getter methods in JacksonConfig are generated by Lombok,
javadoc fails. So, changed from link to just code, which is not awesome,
but it does let javadoc complete successfully.
Closes #284

Fix javadoc of StandardJacksonConfigurations

---

src/main/java/org/kiwiproject/dropwizard/util/resource/ConfigResource.java
src/test/java/org/kiwiproject/dropwizard/util/resource/ConfigResourceTest.java

* Add three constructors to ConfigResource to allow callers to provide a custom ObjectMapper, JsonHelper, or to customize an internally-created ObjectMapper
* Note that the tests are unit tests; without creating separate DropwizardAppExtensions there is not a way to change the resource for each test. Since there are already integration tests, testing the resource class directly seems like an acceptable tradeoff.
Closes #289

Add constructors to ConfigResource for ObjectMapper customization

---

src/main/java/org/kiwiproject/dropwizard/util/health/keystore/KeystoreHealthResults.java
src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJobs.java
src/test/java/org/kiwiproject/dropwizard/util/resource/ConfigResourceTest.java

* Replace usages of KiwiDropwizardDurations.fromDropwizardDuration with the toJavaDuration method on Dropwizard's Duration class
* Change from comment suppressing an unchecked conversion to annotation

Fix deprecated code usage

---

src/main/java/org/kiwiproject/dropwizard/util/health/keystore/BasicCertInfo.java
src/test/java/org/kiwiproject/dropwizard/util/health/keystore/ExpiringKeystoreHealthCheckTest.java

* Use getSubjectX500Principal instead of getSubjectDN
* Use getIssuerX500Principal instead of getIssuerDN
Note that calling getName on the returned X500Principal apparently removes the spaces after the commas in the distinguished names. This is why I changed the tests to ignore whitespace.

Replace usages of deprecated methods in X509Certificate

---

src/main/java/org/kiwiproject/dropwizard/util/startup/PortAssigner.java
src/test/java/org/kiwiproject/dropwizard/util/startup/PortAssignerTest.java

* PortAssigner should set new property disableSniHostCheck, which was added in kiwi 3.2.0
* PortAssigner should set additional properties from TlsContextConfiguration: keyStoreType, keyStoreProvider, trustStoreType, trustStoreProvider, jceProvider, certAlias, and supportedCipherSuites
* Add implNote to javadoc of assignDynamicPorts, which explains that it replaces the HttpsConnectorFactory instances when assigning secure dynamic ports.
* Add tests to verify the secure properties are correctly set on the HttpsConnectorFactory when using secure dynamic ports
* Clean up existing tests by using KiwiAssertJ#assertIsExactType, and also by using assertAll when there are a lot of assertions
Closes #398
Closes #401

Update PortAssigner to set more properties from TlsContextConfiguration

---

src/main/java/org/kiwiproject/dropwizard/util/job/JobExceptionInfo.java
src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJob.java
src/test/java/org/kiwiproject/dropwizard/util/job/JobExceptionInfoTest.java
src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobTest.java

* Add JobExceptionInfo record to contain exception metadata
* Update MonitoredJob to set an AtomicReference containing a JobExceptionInfo object in handleExceptionSafely
* JobExceptionInfoTest mostly courtesy of JetBrains AI !
Closes #392

Retain information about the most recent exception in MonitoredJob

---

src/main/java/org/kiwiproject/dropwizard/util/environment/StandardEnvironmentConfigurations.java
src/test/java/org/kiwiproject/dropwizard/util/environment/StandardEnvironmentConfigurationsTest.java

* Add two methods to StandardEnvironmentConfigurations which provide an easy way to control whether Jersey feature auto-discovery is enabled or disabled.
* Add a new enum, JerseyFeatureStatus, to describe whether a feature should be enabled or disabled
* Both of these methods and then enum are marked as beta features to provide for future API changes
Closes #415

Add methods to control Jersey feature auto-discovery

---

src/main/java/org/kiwiproject/dropwizard/util/environment/StandardEnvironmentConfigurations.java
src/test/java/org/kiwiproject/dropwizard/util/environment/StandardEnvironmentConfigurationsTest.java

* Fix my mistake misnaming the Jersey feature auto-discovery methods
* They were incorrectly named with "Jackson" instead of "Jersey"
* The incorrect names were never published in a release, so there are no breaking changes
Closes #415

Rename Jersey feature-autodiscovery methods

---

src/main/java/org/kiwiproject/dropwizard/util/config/JobSchedule.java
src/test/java/org/kiwiproject/dropwizard/util/config/JobScheduleTest.java

* Use Lombok Jacksonized annotation to on the class to tell Jackson to use the builder when deserializing.
* Add tests of construction and deserialization from JSON and YAML
Closes #422

JobSchedule should respect default initial delay when deserialized

---

src/main/java/org/kiwiproject/dropwizard/util/exception/StandardExceptionMappers.java
src/test/java/org/kiwiproject/dropwizard/util/exception/StandardExceptionMappersTest.java

This makes NoSuchElementExceptionMapper one of our "standard" exception mappers. This is unique to kiwi and does not replace an existing Dropwizard exception mapper.
Closes #424

Register NoSuchElementExceptionMapper in StandardExceptionMappers

---

src/main/java/org/kiwiproject/dropwizard/util/startup/PortAssigner.java
src/test/java/org/kiwiproject/dropwizard/util/resource/ConfigResourceTest.java

* Add more details to the javadoc to better explain the differences in behavior when using HTTP vs HTTPS ports.
* Emphasize the word 'replace' in a debugging log message.
* Make the TestConfig nested class public inside ConfigResourceTest, because IntelliJ flagged this as a case where the class using it (TestApp) was public and had more visibility than a class it was using. While this didn't cause the test any problems, better to listen to IntelliJ when it tells you something! And it's correct that normally, this would have been an issue in production code.
Closes #428

Improve PortAssigner#assignDynamicPorts javadocs

---

src/main/java/org/kiwiproject/dropwizard/util/server/DropwizardConnectors.java
src/test/java/org/kiwiproject/dropwizard/util/server/DropwizardConnectorsTest.java

Add several utility methods to get application and/or admin ports from either a Dropwizard Configuration or DefaultServerFactory.
Also, add scheme() method to ConnectoType enum to get the scheme (http or https).
Closes #450
Closes #453

More utilities to get ports in DropwizardConnectors

---

src/main/java/org/kiwiproject/dropwizard/util/startup/PortAssigner.java
src/test/java/org/kiwiproject/dropwizard/util/startup/PortAssignerTest.java

Even though this does change a public APiI, it does so in a backwards and binary compatible way. So, there is no need for a major version bump.
Closes #444

Change PortAssigner#assignDynamicPorts to return a value

---

src/main/java/org/kiwiproject/dropwizard/util/bundle/PortAssigners.java
src/main/java/org/kiwiproject/dropwizard/util/bundle/StartupLockBundle.java
src/main/java/org/kiwiproject/dropwizard/util/bundle/StartupLockConfiguration.java
src/main/java/org/kiwiproject/dropwizard/util/bundle/StartupLockConfigured.java
src/test/java/org/kiwiproject/dropwizard/util/bundle/MyStartupLockApp.java
src/test/java/org/kiwiproject/dropwizard/util/bundle/MyStartupLockConfig.java
src/test/java/org/kiwiproject/dropwizard/util/bundle/PortAssignersTest.java
src/test/java/org/kiwiproject/dropwizard/util/bundle/StartupLockBundleTest.java
src/test/java/org/kiwiproject/dropwizard/util/bundle/StartupLockConfigurationTest.java
src/test/resources/StartupLockConfigurationTest/startup-lock-config-all-properties.yml
src/test/resources/StartupLockConfigurationTest/startup-lock-config-none.yml
src/test/resources/StartupLockConfigurationTest/startup-lock-config-some-properties.yml

* Add StartupLockConfiguration, which contains startup lock configuration
* Add StartupLockConfigured interface, which defines how the bundle gets the configuration
* Add StartupLockBundle, which acquires a distributed ZooKeeper lock during startup
* Add overloaded portAssignmentFrom to PortAssigners ; it accepts a StartupLockConfiguration
Closes #460

Add bundle that acquires a distributed lock during startup

---

src/main/java/org/kiwiproject/dropwizard/util/bundle/DynamicPortsConfiguration.java

* Include the default values in the docs
* Add additional information about the min/max ports
* Add explanation that a valid TLS config is needed when using secure (HTTP) ports

Enhance DynamicPortsConfiguration javadocs

---

src/main/java/org/kiwiproject/dropwizard/util/bundle/PortAssigners.java
src/main/java/org/kiwiproject/dropwizard/util/startup/PortAssigner.java
src/test/java/org/kiwiproject/dropwizard/util/startup/PortAssignerTest.java

* Add factory method to create PortAssigner.PortAssignment from a boolean
* Add factory method to create PortAssigner.PortSecurity from a boolean
* Add methods to convert between PortAssigner.PortSecurity and Port.Security
Closes #463
Closes #464
Closes #465

Factory/conversion methods in PortAssigner enums

---

src/main/java/org/kiwiproject/dropwizard/util/server/DropwizardConnectors.java

* Change javadoc to say there must be exactly one application/admin port for the "getOnly" methods

Fix Javadoc in DropwizardConnectors

---

src/main/java/org/kiwiproject/dropwizard/util/bundle/DynamicPortsConfiguration.java
src/main/java/org/kiwiproject/dropwizard/util/bundle/StartupLockConfiguration.java
src/main/java/org/kiwiproject/dropwizard/util/startup/PortAssigner.java
src/test/java/org/kiwiproject/dropwizard/util/bundle/MyStartupLockApp.java
src/test/java/org/kiwiproject/dropwizard/util/job/JobErrorHandlersTest.java

* Organize imports in several classes.
* Replace custom methods with new utilities from kiwi in DynamicPortsConfiguration and StartupLockConfiguration.
* Fix missing return javadoc tag in PortAssigner.
* Remove (now) redundant cast in MyStartupLockApp.
* Make StartupLocker field final in MyStartupLockApp.
* Extract duplicate code in JobErrorHandlersTest into method.

Misc code cleanup

---

src/main/java/org/kiwiproject/dropwizard/util/exception/StandardExceptionMappers.java
src/test/java/org/kiwiproject/dropwizard/util/exception/StandardExceptionMappersTest.java

* Make disableDefaultExceptionMapperRegistration public
* Directly call setter method if argument is an AbsractServerFactory
* Enhance exception methods when reflective invocation fails
* Add/update javadocs
Closes #483

Make disableDefaultExceptionMapperRegistration public in StandardExceptionMappers

---

src/main/java/org/kiwiproject/dropwizard/util/exception/StandardExceptionMappers.java

* Add overloaded registerKiwiExceptionMappers methods to StandardExceptionMappers, one accepts Environment and the other accepts JerseyEnvironment.
* Refactor StandardExceptionMappers#register to call the new registerKiwiExceptionMappers method.
* Move call to disableDefaultExceptionMapperRegistration to the top of the #register method.
* Reorder calls to register exception mappers in alphabetical order
Closes #480

Add methods to register kiwi exception mappers

---

src/main/java/org/kiwiproject/dropwizard/util/exception/StandardExceptionMappers.java

* Add overloaded registerReplacementDropwizardExceptionMappers methods to StandardExceptionMappers; one accepts a Dropwizard Environment, the other a JerseyEnvironment
* Update/enhance javadocs with more references
Closes #481

Extract new methods to register replacement exception mappers

---

src/main/java/org/kiwiproject/dropwizard/util/exception/StandardExceptionMappers.java

* This new method does not disable the default Dropwizard ones
* Refactor the original #register method to call the new one
* Minor doc updates to existing #register method
Closes #479

Add new register method to StandardExceptionMappers

---

pom.xml

Update the POM to lock the versions of all kiwi dependencies by adding them to
the dependencyManagement section and removing the explicit versions from the
declarations in the dependencies section.
This will prevent dependency convergence errors whenever dependabot sends us PRs.
This also updates the version of metrics-healthchecks-severity to 2.0.4.  This is the library
where we get convergence errors.
The libraries are:
* dropwizard-curator
* kiwi (was already locked)
* kiwi-test (was already locked)
* metrics-healthchecks-severity
* registry-aware-jersey-client
* service-discovery-client

Manage versions for kiwi library versions

---

src/test/java/org/kiwiproject/dropwizard/util/exception/StandardExceptionMappersTest.java

Add "unused" warning suppression annotation to a parameter which must exist for the test, but we don't need to do anything with.

Sonar cleanup: StandardExceptionMappersTest

---

src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobsTest.java

Don't shadow an instance field. Rename the 'executor' lambda parameter to 'singleThreadExecutor'.

Sonar cleanup: MonitoredJobsTest

---

src/main/java/org/kiwiproject/dropwizard/util/health/CachingHealthCheck.java
src/main/java/org/kiwiproject/dropwizard/util/health/UrlHealthCheck.java

* Fix a few grammatical and spelling errors in CachingHealthCheck
* Replace boolean literal in UrlHealthCheck#shouldExecute

Misc code cleanup in health checks

---

src/test/java/org/kiwiproject/dropwizard/util/health/CachingHealthCheckTest.java

It is never used in the test, so there's no reason for it to exist.

Remove unused MockWebServer from CachingHealthCheckTest

---

src/test/java/org/kiwiproject/dropwizard/util/bundle/MyDynamicPortsApp.java
src/test/java/org/kiwiproject/dropwizard/util/bundle/MyStartupLockApp.java
src/test/java/org/kiwiproject/dropwizard/util/resource/ConfigResourceTest.java
src/test/java/org/kiwiproject/dropwizard/util/startup/StartupLockerTest.java

Fix five "new" issues that Sonar just flagged.
* Add comment to empty methods in test classes (MyDynamicPortsApp, MyStartupLockApp)
* Remove no-args constructor from TestApp in ConfigResourceTest
* Rename non-static fields in nested test classes in StartupLockerTest so they are idiomatic: camelCase, not UPPER_SNAKE_CASE.

Sonar cleanup (2024-07-08)

---

src/main/java/org/kiwiproject/dropwizard/util/exception/JsonExceptionMappers.java

Log JsonProcessingExceptions that do not meet specific criteria for logging specialized messages at WARN or ERROR level, log them as a generic "Unable to process JSON" at WARN level instead of at DEBUG level. This can aid in debugging problems.
Closes #519

Log JsonProcessingExceptions at WARN level by default

---

src/test/java/org/kiwiproject/dropwizard/util/health/UrlHealthCheckTest.java

* Replace RandomStringUtils.randomAlphabetic(...) with RandomStringUtils.secure().nextAlphabetic(...)

Replace deprecated API usage in UrlHealthCheckTest

---

src/main/java/org/kiwiproject/dropwizard/util/bundle/DynamicPortsConfiguration.java
src/main/java/org/kiwiproject/dropwizard/util/startup/AllowablePortRange.java

* DynamicPortsConfiguration had an incorrect value in the Javadocs for the maximum port.
* Clarify that the AllowablePortRange uses inclusive min/max ports.

Fix Javadocs in AllowablePortRange and DynamicPortsConfiguration

---

src/main/java/org/kiwiproject/dropwizard/util/startup/FreePortFinder.java
src/main/java/org/kiwiproject/dropwizard/util/startup/PortAssigner.java
src/main/java/org/kiwiproject/dropwizard/util/startup/RandomFreePortFinder.java
src/test/java/org/kiwiproject/dropwizard/util/startup/PortAssignerTest.java
src/test/java/org/kiwiproject/dropwizard/util/startup/RandomFreePortFinderTest.java

* Add FreePortFinder as a generic port assignment strategy
* Add RandomFreePortFinder as the default strategy, which is consistent with the current behavior of this library.
* Modify PortAssigner to accept a FreePortFinder and use it to get the application and admin ports. If not specified, it will use RandomFreePortFinder as the port assignment strategy.
Closes #536

Introduce the ability to define custom port assignment

---

src/main/java/org/kiwiproject/dropwizard/util/startup/AdjacentFreePortFinder.java
src/main/java/org/kiwiproject/dropwizard/util/startup/IncrementingFreePortFinder.java
src/test/java/org/kiwiproject/dropwizard/util/startup/AdjacentFreePortFinderTest.java
src/test/java/org/kiwiproject/dropwizard/util/startup/IncrementingFreePortFinderTest.java

* Add IncrementingFreePortFinder, which finds the first two open ports within the allowable port range whether adjacent or not. The admin port will always be higher than the application port.
* Add AdjacentFreePortFinder, which finds the first two open and adjacent ports within the allowable port range. The admin port will always be one higher than the application port.
Closes #538
Closes #539

Add incremental and adjacent implementations of FreePortFinder

---

src/test/java/org/kiwiproject/dropwizard/util/startup/AdjacentFreePortFinderTest.java

* Add test to ensure it finds last two ports in range when all others are in use
* Add test to ensure it throws exception when all but last port in range are in use

Add more tests in AdjacentFreePortFinderTest

---

src/test/java/org/kiwiproject/dropwizard/util/startup/FreePortFinderTest.java

Change FreePortFinderTest to use DropwizardConfigurations from kiwi-test to parse a Dropwizard configuration from YAML.

Refactor FreePortFinderTest to use existing kiwi-test function

---

src/main/java/org/kiwiproject/dropwizard/util/bundle/StartupLockBundle.java
src/main/java/org/kiwiproject/dropwizard/util/startup/StartupLocker.java

* Add DEBUG logging in StartupLockBundle that contains the lock path, state of the LockInfo, and message from LockInfo.
* Add INFO level logging in StartupLocker explaining when a lock was not attempted b/c no Zookeeper servers were available.

Add additional logging in startup lock code

---

pom.xml
src/main/java/org/kiwiproject/dropwizard/util/bundle/DynamicPortsConfiguration.java
src/main/java/org/kiwiproject/dropwizard/util/bundle/StartupLockConfiguration.java
src/main/java/org/kiwiproject/dropwizard/util/job/JobExceptionInfo.java
src/main/java/org/kiwiproject/dropwizard/util/startup/PortAssigner.java
src/main/java/org/kiwiproject/dropwizard/util/startup/RandomFreePortFinder.java
src/test/java/org/kiwiproject/dropwizard/util/config/JobScheduleTest.java

* Replace Checker Nullable with JSpecify
* Remove redundant warning suppression in StartupLockConfiguration

Replace Checker annotations with JSpecify; remove redundant warning

---

src/main/java/org/kiwiproject/dropwizard/util/health/MonitoredJobHealthCheck.java

* Instead of calculating the warning threshold every time health check details are created, use the (final) warningThreshold field. This is possible because calculateWarningThreshold (renamed from getWarningThreshold) always returns the same value since expectedFrequency and thresholdFactor are final primitive values.
* Rename getWarningThreshold method to calculateWarningThreshold to make it clear that there is a calculation being done; it is not just a getter method.

Use cached field value in MonitoredJobHealthCheck for health details

---

src/main/java/org/kiwiproject/dropwizard/util/health/MonitoredJobHealthCheck.java
src/test/java/org/kiwiproject/dropwizard/util/health/MonitoredJobHealthCheckTest.java

* Rename private fields and local vars in MonitoredJobHealthCheck to be more consistent in terms of what is a timestamp, what is a duration, what the unit is, etc. It's not perfect, but it's better.
* Change calculateWarningThreshold to a static method and add arguments for clarity.
* Rename several method parameters for clarity.

Code cleanup: renaming fields and vars in MonitoredJobHealthCheck

---

src/main/java/org/kiwiproject/dropwizard/util/health/MonitoredJobHealthCheck.java
src/test/java/org/kiwiproject/dropwizard/util/health/MonitoredJobHealthCheckTest.java

* Rename the lastFailure detail to lastFailureTimestamp.
* Rename the lastSuccess detail to lastSuccessTimestamp.
* Rename the lastExecutionTimeMs detail to lastSuccessfulExecutionDurationMs.
* Rename the expectedFrequencyMs detail to expectedJobFrequencyMs.
* Rename the errorWarningDurationMs detail to recentErrorWarningDurationMs.
* Rename the warningThresholdMs detail to warningThresholdDurationMs.
* Add lastFailureTime detail (human-readable of lastSuccessTimestamp).
* Add lastSuccessfulExecutionDuration detail (human-readable of lastSuccessfulExecutionDurationMs).
* Add expectedJobFrequency detail (human-readable of expectedJobFrequencyMs).
* Add warningThresholdDuration detail (human-readable of warningThresholdDurationMs).
* Add recentErrorWarningDuration detail (human-readable of …

Make MonitoredJobHealthCheck details consistent and human-readable

---

src/main/java/org/kiwiproject/dropwizard/util/job/MonitoredJobs.java
src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobTest.java
src/test/java/org/kiwiproject/dropwizard/util/job/MonitoredJobsTest.java

* Add the registeredJobNames method to return a sorted, unmodifiable set containing the names of the registered jobs.
* Add the clearRegisteredJobNames method to clear out the previously registered job names
* Add more validation of the JobSchedule to ensure that the initial delay is non-negative and that the interval delay is positive.
* Update Javadocs of the registerJob methods to state that an IllegalArgumentException is thrown if a job has already been registered with the same name.
* Change the dummy tasks in MonitoredJobTest and MonitoredJobsTest
to use Guava's Runnables.doNothing()
Closes #610
Closes #613

Add the ability to get and clear registered job names to MonitoredJobs
